    server {
 	 server_name  minecraft.daktoinc.co.uk;

        listen 443 ssl;
        listen [::]:443 ssl;
        ssl_certificate /etc/cloudflare/pem;
        ssl_certificate_key /etc/cloudflare/key;
        #charset koi8-r;

        #access_log  logs/host.access.log  main;


	location / {
	    root   /var/lib/daksite/mcmap;
	    index  index.html;
	}

	location /smp {
		return 301 ..;
	}

	location /anarchy {
		return 301 ..;
	}

	location /creative {
		return 301 ..;
	}


	location /lobby {
		return 301 ..;
	}

	location /terra {
		return 301 ..;
	}

	location /archive {
		return 301 ..;
	}

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page  404 500 502 503 504 /50x.html;
	
	location /up {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8123/up;
    		sub_filter '"OnlyQwQ",' '"DKI Admin",';
    		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
        	sub_filter_once off;
        }

	location /tiles {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8123/tiles;
    		sub_filter '"OnlyQwQ",' '"DKI Admin",';
    		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
        	sub_filter_once off;
        }
	location /arcup {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8190/up;
	}

	location /arctiles {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8190/tiles;
	}

		location /cumup {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8124/up;

    		sub_filter '"OnlyQwQ",' '"DKI Admin",';
    		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
        	sub_filter_once off;
        }

	location /cumtiles {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8124/tiles;

    		sub_filter '"OnlyQwQ",' '"DKI Admin",';
    		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
        	sub_filter_once off;
        }

	location /terup {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8127/up;

		sub_filter '"OnlyQwQ",' '"DKI Admin",';
		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
		sub_filter_once off;
	}

	location /tertiles {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8127/tiles;

		sub_filter '"OnlyQwQ",' '"DKI Admin",';
		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
		sub_filter_once off;
	}

location /anup  {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8129/up;

		sub_filter '"OnlyQwQ",' '"DKI Admin",';
		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
		sub_filter_once off;
        }

location /antiles {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8129/tiles;

		sub_filter '"OnlyQwQ",' '"DKI Admin",';
		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
		sub_filter_once off;
	}

location /loup {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8126/up;

		sub_filter '"OnlyQwQ",' '"DKI Admin",';
		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
		sub_filter_once off;
	}

location /lotiles {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://127.0.0.1:8126/tiles;

		sub_filter '"OnlyQwQ",' '"DKI Admin",';
		sub_filter '"Dakto_",' '"DKI Owner",';
sub_filter_types '*';
		sub_filter_once off;
        }
 
    }



